CREATE TABLE users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash CHAR(60) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO users (username, email, password_hash, created_at) VALUES
('user1', 'user1@example.com', 'password1_hash', NOW()),
('user2', 'user2@example.com', 'password2_hash', NOW()),
('user3', 'user3@example.com', 'password3_hash', NOW()),
('user4', 'user4@example.com', 'password4_hash', NOW()),
('user5', 'user5@example.com', 'password5_hash', NOW()),
('user6', 'user6@example.com', 'password6_hash', NOW()),
('user7', 'user7@example.com', 'password7_hash', NOW()),
('user8', 'user8@example.com', 'password8_hash', NOW()),
('user9', 'user9@example.com', 'password9_hash', NOW()),
('user10', 'user10@example.com', 'password10_hash', NOW());

CREATE TABLE blogs (
    blog_id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    content TEXT,
    author_id INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO blogs (title, content, author_id, created_at) VALUES
('First Blog', 'This is the content of the first blog.', 1, NOW()),
('Second Blog', 'Content of the second blog goes here.', 2, NOW()),
('Third Blog', 'Content of the third blog.', 3, NOW()),
('Fourth Blog', 'Content for the fourth blog.', 4, NOW()),
('Fifth Blog', 'Content of the fifth blog post.', 5, NOW()),
('Sixth Blog', 'Content of the sixth blog entry.', 6, NOW()),
('Seventh Blog', 'Content for the seventh blog.', 7, NOW()),
('Eighth Blog', 'Content of the eighth blog post.', 8, NOW()),
('Ninth Blog', 'Content of the ninth blog entry.', 9, NOW()),
('Tenth Blog', 'Content for the tenth blog.', 10, NOW());

CREATE TABLE comments (
    comment_id INT AUTO_INCREMENT PRIMARY KEY,
    blog_id INT,
    user_id INT,
    comment_text TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO comments (blog_id, user_id, comment_text, created_at) VALUES
(1, 1, 'This is comment number 1 on the blog.', NOW()),
(1, 2, 'This is comment number 2 on the blog.', NOW()),
(1, 3, 'This is comment number 3 on the blog.', NOW()),
(1, 4, 'This is comment number 4 on the blog.', NOW()),
(1, 5, 'This is comment number 5 on the blog.', NOW()),
(1, 6, 'This is comment number 6 on the blog.', NOW()),
(1, 7, 'This is comment number 7 on the blog.', NOW()),
(1, 8, 'This is comment number 8 on the blog.', NOW()),
(1, 9, 'This is comment number 9 on the blog.', NOW()),
(1, 10, 'This is comment number 10 on the blog.', NOW()),
(2, 1, 'This is comment number 1 on the second blog.', NOW()),
(2, 2, 'This is comment number 2 on the second blog.', NOW()),
(2, 3, 'This is comment number 3 on the second blog.', NOW()),
(2, 4, 'This is comment number 4 on the second blog.', NOW()),
(2, 5, 'This is comment number 5 on the second blog.', NOW()),
(2, 6, 'This is comment number 6 on the second blog.', NOW()),
(2, 7, 'This is comment number 7 on the second blog.', NOW()),
(2, 8, 'This is comment number 8 on the second blog.', NOW()),
(2, 9, 'This is comment number 9 on the second blog.', NOW()),
(2, 10, 'This is comment number 10 on the second blog.', NOW()),
(3, 1, 'This is comment number 1 on the third blog.', NOW()),
(3, 2, 'This is comment number 2 on the third blog.', NOW()),
(3, 3, 'This is comment number 3 on the third blog.', NOW()),
(3, 4, 'This is comment number 4 on the third blog.', NOW()),
(3, 5, 'This is comment number 5 on the third blog.', NOW()),
(3, 6, 'This is comment number 6 on the third blog.', NOW()),
(3, 7, 'This is comment number 7 on the third blog.', NOW()),
(3, 8, 'This is comment number 8 on the third blog.', NOW()),
(3, 9, 'This is comment number 9 on the third blog.', NOW()),
(3, 10, 'This is comment number 10 on the third blog.', NOW()),
(4, 1, 'This is comment number 1 on the fourth blog.', NOW()),
(4, 2, 'This is comment number 2 on the fourth blog.', NOW()),
(4, 3, 'This is comment number 3 on the fourth blog.', NOW()),
(4, 4, 'This is comment number 4 on the fourth blog.', NOW()),
(4, 5, 'This is comment number 5 on the fourth blog.', NOW()),
(4, 6, 'This is comment number 6 on the fourth blog.', NOW()),
(4, 7, 'This is comment number 7 on the fourth blog.', NOW()),
(4, 8, 'This is comment number 8 on the fourth blog.', NOW()),
(4, 9, 'This is comment number 9 on the fourth blog.', NOW()),
(4, 10, 'This is comment number 10 on the fourth blog.', NOW()),
(5, 1, 'This is comment number 1 on the fifth blog.', NOW()),
(5, 2, 'This is comment number 2 on the fifth blog.', NOW()),
(5, 3, 'This is comment number 3 on the fifth blog.', NOW()),
(5, 4, 'This is comment number 4 on the fifth blog.', NOW()),
(5, 5, 'This is comment number 5 on the fifth blog.', NOW()),
(5, 6, 'This is comment number 6 on the fifth blog.', NOW()),
(5, 7, 'This is comment number 7 on the fifth blog.', NOW()),
(5, 8, 'This is comment number 8 on the fifth blog.', NOW()),
(5, 9, 'This is comment number 9 on the fifth blog.', NOW()),
(5, 10, 'This is comment number 10 on the fifth blog.', NOW()),
(6, 1, 'This is comment number 1 on the sixth blog.', NOW()),
(6, 2, 'This is comment number 2 on the sixth blog.', NOW()),
(6, 3, 'This is comment number 3 on the sixth blog.', NOW()),
(6, 4, 'This is comment number 4 on the sixth blog.', NOW()),
(6, 5, 'This is comment number 5 on the sixth blog.', NOW()),
(6, 6, 'This is comment number 6 on the sixth blog.', NOW()),
(6, 7, 'This is comment number 7 on the sixth blog.', NOW()),
(6, 8, 'This is comment number 8 on the sixth blog.', NOW()),
(6, 9, 'This is comment number 9 on the sixth blog.', NOW()),
(6, 10, 'This is comment number 10 on the sixth blog.', NOW()),
(7, 1, 'This is comment number 1 on the seventh blog.', NOW()),
(7, 2, 'This is comment number 2 on the seventh blog.', NOW()),
(7, 3, 'This is comment number 3 on the seventh blog.', NOW()),
(7, 4, 'This is comment number 4 on the seventh blog.', NOW()),
(7, 5, 'This is comment number 5 on the seventh blog.', NOW()),
(7, 6, 'This is comment number 6 on the seventh blog.', NOW()),
(7, 7, 'This is comment number 7 on the seventh blog.', NOW()),
(7, 8, 'This is comment number 8 on the seventh blog.', NOW()),
(7, 9, 'This is comment number 9 on the seventh blog.', NOW()),
(7, 10, 'This is comment number 10 on the seventh blog.', NOW()),
(8, 1, 'This is comment number 1 on the eighth blog.', NOW()),
(8, 2, 'This is comment number 2 on the eighth blog.', NOW()),
(8, 3, 'This is comment number 3 on the eighth blog.', NOW()),
(8, 4, 'This is comment number 4 on the eighth blog.', NOW()),
(8, 5, 'This is comment number 5 on the eighth blog.', NOW()),
(8, 6, 'This is comment number 6 on the eighth blog.', NOW()),
(8, 7, 'This is comment number 7 on the eighth blog.', NOW()),
(8, 8, 'This is comment number 8 on the eighth blog.', NOW()),
(8, 9, 'This is comment number 9 on the eighth blog.', NOW()),
(8, 10, 'This is comment number 10 on the eighth blog.', NOW()),
(9, 1, 'This is comment number 1 on the ninth blog.', NOW()),
(9, 2, 'This is comment number 2 on the ninth blog.', NOW()),
(9, 3, 'This is comment number 3 on the ninth blog.', NOW()),
(9, 4, 'This is comment number 4 on the ninth blog.', NOW()),
(9, 5, 'This is comment number 5 on the ninth blog.', NOW());

